version: '3.4'

services:
  dockerwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: myregistry/dockerwebapp
    build:
      context: .
      dockerfile: AmazingCo.Api/Dockerfile
    ports:
            - "8000:80"
    depends_on:
      - db     
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "SecurePassword001"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"